version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
  build:
    commands:
      - echo "Hello from AWS CodeBuild!"
      - echo "Build successful!"

artifacts:
  files:
    - '**/*'
